import { getDateRelative } from "../utils/dateUtils";
import { Event } from "../types";

export const MOCK_EVENTS: Event[] = [
    {
        id: "e1",
        title: "AI Workshop",
        faculty: "Faculty of Computing",
        subcategory: "Workshop",
        organizer: "Computing Society",
        date: getDateRelative(2),
        timeStart: "14:00",
        timeEnd: "17:00",
        location: "Innovation Lab",
        maxParticipants: 60,
        registered: 52,
        banner: null,
        categoryColor: "#3B82F6",
        description: "Introduction to AI and machine learning. Hands-on sessions covering neural networks and practical applications.",
        trending: true,
    },
    {
        id: "e2",
        title: "Cybersecurity Seminar",
        faculty: "Faculty of Computing",
        subcategory: "Seminar",
        date: getDateRelative(5),
        timeStart: "09:00",
        timeEnd: "12:00",
        location: "Main Auditorium",
        maxParticipants: 150,
        registered: 140,
        banner: null,
        categoryColor: "#60A5FA",
        description: "Industry experts discussing the latest trends and threats in the cybersecurity landscape.",
    },
    {
        id: "e3",
        title: "Startup Pitch Night",
        faculty: "School of Business",
        subcategory: "Competition",
        date: getDateRelative(7),
        timeStart: "18:00",
        timeEnd: "21:00",
        location: "Business Hub",
        maxParticipants: 200,
        registered: 185,
        banner: null,
        categoryColor: "#F59E0B",
        description: "Watch student entrepreneurs pitch their startup ideas to a panel of real-world investors.",
        trending: true,
    },
    {
        id: "e4",
        title: "Marketing Strategy Talk",
        faculty: "School of Business",
        subcategory: "Guest Lecture",
        date: getDateRelative(10),
        timeStart: "15:00",
        timeEnd: "17:00",
        location: "Lecture Hall B",
        maxParticipants: 100,
        registered: 80,
        banner: null,
        categoryColor: "#FBBF24",
        description: "A deep dive into modern digital marketing strategies for startups and established brands.",
    },
    {
        id: "e5",
        title: "Sustainable Design Talk",
        faculty: "School of Architecture",
        subcategory: "Guest Lecture",
        date: getDateRelative(4),
        timeStart: "10:00",
        timeEnd: "12:00",
        location: "Design Studio",
        maxParticipants: 80,
        registered: 75,
        banner: null,
        categoryColor: "#10B981",
        description: "Exploring eco-friendly architectural practices and sustainable urban planning.",
    },
    {
        id: "e6",
        title: "Psychology Lecture",
        faculty: "Faculty of Humanities and Sciences",
        subcategory: "Lecture",
        date: getDateRelative(12),
        timeStart: "13:00",
        timeEnd: "15:00",
        location: "Science Block D",
        maxParticipants: 120,
        registered: 95,
        banner: null,
        categoryColor: "#8B5CF6",
        description: "Understanding human behavior and cognitive psychology in the modern digital age.",
    },
    {
        id: "e7",
        title: "Moot Court Competition",
        faculty: "School of Law",
        subcategory: "Competition",
        date: getDateRelative(14),
        timeStart: "09:00",
        timeEnd: "16:00",
        location: "Law Tribunal",
        maxParticipants: 50,
        registered: 48,
        banner: null,
        categoryColor: "#EF4444",
        description: "Annual moot court competition focusing on constitutional law and civil rights.",
        trending: true,
    },
    {
        id: "e8",
        title: "Culinary Innovation Workshop",
        faculty: "School of Hospitality Management",
        subcategory: "Workshop",
        date: getDateRelative(8),
        timeStart: "14:00",
        timeEnd: "18:00",
        location: "Demo Kitchen",
        maxParticipants: 30,
        registered: 30,
        banner: null,
        categoryColor: "#EC4899",
        description: "Hands-on culinary session exploring molecular gastronomy and modern plating techniques.",
    },
    {
        id: "e9",
        title: "Interfaculty Football Tournament",
        faculty: "Miscellaneous",
        subcategory: "Sports",
        date: getDateRelative(15),
        timeStart: "08:00",
        timeEnd: "18:00",
        location: "Main Sports Ground",
        maxParticipants: 500,
        registered: 350,
        banner: null,
        categoryColor: "#F97316",
        description: "The biggest sports event of the semester. Come cheer for your faculty team!",
    },
    {
        id: "e10",
        title: "Campus Open Mic Night",
        faculty: "Miscellaneous",
        subcategory: "Music",
        date: getDateRelative(3),
        timeStart: "19:00",
        timeEnd: "22:00",
        location: "Open Air Theater",
        maxParticipants: 300,
        registered: 250,
        banner: null,
        categoryColor: "#A855F7",
        description: "An evening of raw talent featuring acoustic sets, stand-up comedy, and poetry.",
        trending: true,
    },
    {
        id: "e11",
        title: "Public Speaking Workshop",
        faculty: "Miscellaneous",
        subcategory: "Clubs & Societies",
        organizer: "Gavel Club",
        date: getDateRelative(11),
        timeStart: "16:00",
        timeEnd: "18:00",
        location: "Seminar Room 1",
        maxParticipants: 40,
        registered: 35,
        banner: null,
        categoryColor: "#14B8A6",
        description: "Overcome stage fright and learn the art of effective communication and speech crafting.",
    },
    {
        id: "e12",
        title: "Community Service Meetup",
        faculty: "Miscellaneous",
        subcategory: "Clubs & Societies",
        organizer: "Leo Club",
        date: getDateRelative(18),
        timeStart: "10:00",
        timeEnd: "13:00",
        location: "Student Lounge",
        maxParticipants: 100,
        registered: 85,
        banner: null,
        categoryColor: "#F43F5E",
        description: "Join us for our monthly meetup to discuss upcoming community service projects and volunteer opportunities.",
    }
];
