import { getDateRelative } from "../utils/dateUtils";
import { Event } from "../types";

export const MOCK_EVENTS: Event[] = [
    {
        id: "e1",
        title: "AI & Machine Learning Workshop",
        category: "Tech",
        date: getDateRelative(2),
        timeStart: "14:00",
        timeEnd: "17:00",
        venue: "CS Lab Block A",
        club: "Computer Science Club",
        maxParticipants: 60,
        registered: 52,
        banner: null,
        categoryColor: "#3B82F6",
        description:
            "Dive into practical machine learning with hands-on sessions covering neural networks, NLP, and computer vision. Industry mentors will guide you through real-world case studies and cutting-edge tools.",
        trending: true,
    },
    {
        id: "e2",
        title: "Inter-University Cricket Finals",
        category: "Sports",
        date: getDateRelative(5),
        timeStart: "09:00",
        timeEnd: "16:00",
        venue: "Main Sports Ground",
        club: "Sports Council",
        maxParticipants: 200,
        registered: 152,
        banner: null,
        categoryColor: "#F97316",
        description:
            "Cheer for our university cricket team in the final showdown of the inter-university cricket championship. Free entry for all students with ID.",
    },
    {
        id: "e3",
        title: "Evening of Jazz & Fusion",
        category: "Cultural",
        date: getDateRelative(1),
        timeStart: "18:30",
        timeEnd: "21:00",
        venue: "Open Air Theater",
        club: "Music Society",
        maxParticipants: 300,
        registered: 215,
        banner: null,
        categoryColor: "#A855F7",
        description:
            "An enchanting evening of jazz, fusion, and world music performed by our talented music society members and special guest artists.",
        trending: true,
    },
    {
        id: "e4",
        title: "UX Design Mastery Class",
        category: "Tech",
        date: getDateRelative(12),
        timeStart: "09:00",
        timeEnd: "16:00",
        venue: "Design Studio, Building 4",
        club: "Design Collective",
        maxParticipants: 40,
        registered: 38,
        banner: null,
        categoryColor: "#3B82F6",
        description:
            "Learn the fundamentals of user experience design from industry experts. This hands-on workshop covers wireframing, prototyping, and user testing.",
        trending: true,
    },
    {
        id: "e5",
        title: "Career Fair 2024",
        category: "Career",
        date: getDateRelative(15),
        timeStart: "10:00",
        timeEnd: "17:00",
        venue: "Main Auditorium",
        club: "Career Services",
        maxParticipants: 1000,
        registered: 450,
        banner: null,
        categoryColor: "#10B981",
        description: "Connect with top employers from various industries. Bring your resume and prepare for on-the-spot interviews.",
    },
    {
        id: "e6",
        title: "Research Paper Writing",
        category: "Academic",
        date: getDateRelative(8),
        timeStart: "15:00",
        timeEnd: "18:00",
        venue: "Library Seminar Room",
        club: "Academic Excellence Society",
        maxParticipants: 100,
        registered: 65,
        banner: null,
        categoryColor: "#6366F1",
        description: "Master the art of academic writing and publishing. Learn how to structure your research and cite sources correctly.",
    }
];
